blueprint:
  name: Detached Light
  description: Toggle the light state by signal, without turning it off.
  domain: automation
  source_url: https://github.com/dafo90/home-assistant-blueprints/blob/master/detached_light.yaml
  input:
    button_entity:
      name: Button
      selector:
        entity:
          domain: binary_sensor
    light_target:
      name: Light
      selector:
        target:
          entity:
            domain: light

mode: single

trigger:
  - platform: state
    entity_id: !input button_entity
    from: "off"
    to: "on"
  - platform: state
    entity_id: !input button_entity
    from: "on"
    to: "off"

action:
  - alias: "Toggle the light state"
    service: light.toggle
    target: !input light_target
