blueprint:
  name: Sonoff SNZB-03 Motion-activated Light
  description: Turn on a light when motion is detected.
  domain: automation
  source_url: https://github.com/dafo90/home-assistant-blueprints/blob/master/snzb03_motion_light.yaml
  input:
    motion_entities:
      name: Motion Sensor
      selector:
        entity:
          multiple: true
          domain: binary_sensor
          device_class: motion
    light_target:
      name: Light
      selector:
        target:
          entity:
            domain: light
    no_motion_wait:
      name: Wait time
      description: Time to leave the light on after last motion is detected (60s minimum due to the limitations of the SNZB-03 sensor).
      default: 120
      selector:
        number:
          min: 60
          max: 3600
          unit_of_measurement: seconds

mode: single

trigger:
  - platform: state
    entity_id: !input motion_entities
    from: "off"
    to: "on"
  - platform: state
    entity_id: !input motion_entities
    from: "on"
    to: "off"

action:
  - alias: "Turn on the light"
    if:
      - condition: state
        entity_id: !input motion_entities
        match: any
        state: "on"
    then:
      - service: light.turn_on
        target: !input light_target
  - alias: "Turn off the light after delay"
    if:
      - condition: state
        entity_id: !input motion_entities
        match: all
        state: "off"
    then:
      - variables:
          total_second_no_motion_wait: !input no_motion_wait
      - alias: "Wait the number of seconds that has been set"
        delay: "{{ total_second_no_motion_wait | int - 60 }}"
      - alias: "Check if the motion sensor has been activated in the meantime"
        if:
          - condition: state
            entity_id: !input motion_entities
            match: all
            state: "off"
        then:
          - alias: "Turn off the light"
            service: light.turn_off
            target: !input light_target
