blueprint:
  name: Vacuum robot - Start cleaning house
  description: Start the robot to clean the whole house on the specified days and at the specified time, only if no one is home (based on phone presence). The robot will return to the base independently.
  source_url: https://github.com/dafo90/home-assistant-blueprints/blob/master/vacuum_cleaning_schedule.yaml
  domain: automation
  input:
    vacuum_entity:
      name: Vacuum robot
      selector:
        entity:
          domain: vacuum
    start_time:
      name: Start time
      selector:
        time:
    days_of_week:
      name: Days of the week
      selector:
        select:
          multiple: true
          options:
            - mon
            - tue
            - wed
            - thu
            - fri
            - sat
            - sun
    person_device_trackers:
      name: Devices to monitor the presence
      default: []
      selector:
        entity:
          multiple: true
          domain: device_tracker

mode: single

variables:
  person_device_trackers: !input person_device_trackers

trigger:
  - platform: time
    at: !input start_time

condition:
  - condition: time
    weekday: !input days_of_week
  - condition: template
    value_template: >
      {% for device in person_device_trackers %}
        {% if not is_state(device, 'not_home') %}
          {{ false }}
        {% endif %}
      {% endfor %}
      {{ true }}

action:
  - service: vacuum.start
    target:
      entity_id: !input vacuum_entity
