blueprint:
  name: Vacuum robot - Ensure is docked
  description: Ensure that on the specified days and at the specified time (or when the battery is low) the vacuum robot is docked, otherwise it will be returned to base.
  source_url: https://github.com/dafo90/home-assistant-blueprints/blob/master/vacuum_ensure_docked.yaml
  domain: automation
  input:
    vacuum_entity:
      name: Vacuum robot
      selector:
        entity:
          domain: vacuum
    check_time:
      name: Check time
      selector:
        time:
    days_of_week:
      name: Days of the week
      selector:
        select:
          multiple: true
          options:
            - mon
            - tue
            - wed
            - thu
            - fri
            - sat
            - sun
    battery_threshold:
      name: Battery threshold
      default: 10
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
          mode: slider
    person_device_trackers:
      name: Devices to monitor the presence
      default: null
      selector:
        multiple: true
        default: []
        entity:
          domain: device_tracker

mode: single

variables:
  person_device_trackers: !input person_device_trackers

trigger:
  - platform: template
    value_template: >
      {% for device in person_device_trackers %}
        {% if is_state(device, 'home') and 
              trigger.to_state.entity_id == device and 
              trigger.from_state.state != 'home' %}
          {{ true }}
        {% endif %}
      {% endfor %}
      {{ false }}
  - platform: time
    at: !input check_time
  - platform: numeric_state
    entity_id: !input vacuum_entity
    attribute: battery_level
    below: !input battery_threshold

condition:
  - condition: time
    weekday: !input days_of_week
  - condition: not
    conditions:
      - condition: state
        entity_id: !input vacuum_entity
        state: "docked"

action:
  - service: vacuum.return_to_base
    target:
      entity_id: !input vacuum_entity
